name: Deploy to GitHub Pages
on:
  push:
    branches: [ release ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node 最新 & pnpm セットアップ（corepack経由）
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          # pnpm cache requires pnpm pre-installed; we enable via corepack below

      - name: Enable corepack & set pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm --version

      - name: Install deps (pnpm, frozen lockfile)
        run: pnpm install --frozen-lockfile

      # Vite の base を自動で渡したい場合は環境変数を設定
      - name: Build
        env:
          VITE_BASE: "/${{ github.event.repository.name }}/"
        run: |
          pnpm build

      - name: Copy SPA 404 (use built index.html)
        run: |
          cp dist/index.html dist/404.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ vars.DIST_DIR || 'dist' }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
